const SONGU_SERVICE_KEY =
  '2RFH4mMUzvWgELfkIuyT%2BXYw8QnnwvE6%2FleSlBPaK1kYRuLaYTCo52vuMwWWQHORhwfIpmOWBfSEA675LytDgw%3D%3D';

const GOOGLE_API_KEY = 'AIzaSyC5xLfDXfz6s9-soQmiQmLHms6QKeXjJ6s';

export { SONGU_SERVICE_KEY, GOOGLE_API_KEY };
